* ============================================================
* REPORT.prg  —  WebBase-III Report Engine showcase
* Demonstrates: CREATE REPORT, MODIFY REPORT, REPORT FORM,
*               LIST REPORTS, DELETE REPORT
* ============================================================

USE DATABASE REPORTDEMO
DROP TABLE SALES
CREATE TABLE SALES (REGION CHAR(20), PRODUCT CHAR(30), AMOUNT NUM(10,2), QTY NUM(6))
USE SALES
INDEX ON REGION TO BYREGION

APPEND RECORD
REPLACE REGION WITH "North", PRODUCT WITH "Widget A", AMOUNT WITH 1200.00, QTY WITH 10
APPEND RECORD
REPLACE REGION WITH "North", PRODUCT WITH "Widget B", AMOUNT WITH 850.50, QTY WITH 7
APPEND RECORD
REPLACE REGION WITH "South", PRODUCT WITH "Widget A", AMOUNT WITH 2100.00, QTY WITH 18
APPEND RECORD
REPLACE REGION WITH "South", PRODUCT WITH "Gadget X", AMOUNT WITH 3400.75, QTY WITH 25
APPEND RECORD
REPLACE REGION WITH "West", PRODUCT WITH "Gadget X", AMOUNT WITH 975.00, QTY WITH 8

SET INDEX TO BYREGION

LIST REPORTS

CLEAR
@ 2, 5 SAY "Report demo complete. Run 'CREATE REPORT salesrpt' to create a report."
